### ISSUE TITLE
Utilizacion de motores de paso tipo NEMA o motores de VCC continua?

### ISSUE THREAD

**Issue by marcos-mendez** [popsolutions/openventilator#1]

**Comment by Capicua44** [comment]
Esto define totalmente el proyecto, quando hablamos de  1,5 Nm según la referencia del MIT .
Los NEMA 17 entregan sin reducción 05 Nm  por lo que me informo Jeremias...  precisaríamos tres motores sincronizados en paralelo. A lo que se suma el problema de las estructuras y las duas que surgen. Lo extrudado en 3 D soportaría? La correa y los engranajes tendrían que ser redimensionados, mismo que utilizemos reductores desde la velocidad y siempre que el motor responda.  Creo que tenemos que evaluar la posibilidad cambiar el proyecto para un sistema neumático, con válvulas de bajo costo, eventualmente con fole, o seguir el proyecto con motores de continua, leva.  Arduino trabajando en PWM y  puente en H.

**Comment by marcos-mendez** [comment]
This issue was closed as NEMA 17 and NEMA 23 shown to be completly unsuited for ventilators needs. Only NEMA 24 with 90% of the power limit would work. This is expensive and a bad solution for a global problem
