### ISSUE TITLE
Measurement of air pressure within the patient's airway

### ISSUE THREAD

**Issue by marcos-mendez** [popsolutions/openventilator#2]
We are trying to find a sensor with afordable price that can be used in this case scenerai, it gotta have a fast response to preassure variation so the machine can stop the ventilation movment and and not harm the pulmonary alveoli

I found this cheap 2mm sensor i don't know it can be used. 

<img src="https://alexnld.com/wp-content/uploads/2015/07/SKU236753-7.jpg"

**Comment by wahingt2n** [comment]
if we use this sensor, we have to decide were we will put them, and then we can do a printed housing for the sensors

**Comment by marcos-mendez** [comment]
Sensors tested today. We reached a sutable solution on water pipe tubing sensor with ultrasound, and also Arduino Sensors. Closing this issue
