### ISSUE TITLE
specs about the valves

### ISSUE THREAD

**Issue by arielhasidim** [popsolutions/openventilator#21]
Hi guy,
at the "valves" folder commit you mentioned: "Updated the valves thanks to openair.org".
I don't think thats the right domain.

I want to read more about the PEEP valve, can someone direct me to the right place?

cheers

**Comment by marcos-mendez** [comment]
theopenairproject.org

**Comment by marcos-mendez** [comment]
Issue closed, now we have water colum PEEP Valve. OpenAir Project Peeo doesnt work. Ethan joined the team and offered a better solution
