### ISSUE TITLE
Filtering the expired air by the patient in order to reduce the surrounding contamination.

### ISSUE THREAD

**Issue by marcos-mendez** [popsolutions/openventilator#3]
What type of filter can we use? According to information from Paper MIT that we researched, the limit would be one micron, but it is necessary to find a cheap and reliable material that can be used in these sanitary conditions in order to allow the equipment to be safe for people around the patient in order to that the appliance does not contaminate further

**Comment by wahingt2n** [comment]
i found this online, can we use something like this water filter, contained in a 3d printed housing?
[https://www.amazon.com/-/es/filtro-155384-bp-420-polipropileno-Micron/dp/B0067GPSP8/ref=sr_1_2?dchild=1&keywords=1%2Bmicron%2Bfilter&qid=1584737103&sr=8-2&th=1](url)

**Comment by marcos-mendez** [comment]
Here is some documentation about HEPA filters and how it can provide 0.5um micras (recomended  is 1) as a cheap solution. Also ultra violet light could kill virus and bacteria

https://pt.wikipedia.org/wiki/Filtro_HEPA

**Comment by marcos-mendez** [comment]
> Here is some documentation about HEPA filters and how it can provide 0.5um micras (recomended is 1) as a cheap solution. Also ultra violet light could kill virus and bacteria
> 
> https://pt.wikipedia.org/wiki/Filtro_HEPA

Notice the Biomedical Aplication section

**Comment by wahingt2n** [comment]
do you know witch one is the correct ?

classe HEPA	retenção (total)	retenção (local)
E10	                > 85%	---
E11          	> 95%	---
E12          	> 99.5%	---
H13         	> 99.95%         	> 99.75%
H14	                > 99.995%	        > 99.975%
U15           	> 99.9995%	        > 99.9975%
U16           	> 99.99995%    	> 99.99975%
U17	                > 99.999995%	        > 99.9999%

**Comment by marcos-mendez** [comment]
Based on this documents https://www.cdc.gov/coronavirus/2019-ncov/hcp/respirator-use-faq.html and also this document i imagine that N95 is the Medical Standard

**Comment by wahingt2n** [comment]
if i understood this right, it means that e11 inclusive and above, that´s right?

**Comment by marcos-mendez** [comment]
Yes but for safety reasons i would choose the E12 one

**Comment by marcos-mendez** [comment]
Please also notice this documentation https://docs.google.com/document/d/1-71FJTmI1Q1kjSDLP0EegMERjg_0kk_7UfaRE4r66Mg/edit?fbclid=IwAR21RNqzjq14fV_DypWk8haaHxGCY7a0ApF_DSOaKR609yoj6T3pLI9oJ80

**Comment by brancante** [comment]
What about a different approach? 
This Coronavirus is very sensitive to temperatures above 26 degrees Celsius, so heating the exhaust maybe could do the trick. We could try using a Mica heating band. It is very inexpensive and reliable.

**Comment by marcos-mendez** [comment]
It is not 26 it is 60 degrees and a heating solution would consume to much
energy

Em qui., 26 de mar. de 2020 às 22:13, brancante <notifications@github.com>
escreveu:
