### ISSUE TITLE
if we cant get the plastic bottles for the respirator, we have to develop a replacement

### ISSUE THREAD

**Issue by wahingt2n** [popsolutions/openventilator#6]
talking to Jere, we came across the possibility that we might come across the shortage of plastic bottles for the respirators, so maybe we can came with an alternative solution.

i thought it might be a good idea to search the idea of making the variable volume chamber with neoprene, or other flexible material. we could use a frame in the middle and 1 sheet on each side, we can also use  a linear actuator in the sides, i will sketch the idea

**Comment by wahingt2n** [comment]
![IMG_20200320_192609](https://user-images.githubusercontent.com/62440708/77210911-f1319b00-6ae0-11ea-91c8-47d80ca8d5bc.jpg)

**Comment by ovix-hub** [comment]
excellent washington! Please if you have technical details of the matter and commercial references of the same

**Comment by wahingt2n** [comment]
> excellent washington! Please if you have technical details of the matter and commercial references of the same

i think we can use neoprene (like the one that is used for the molding process of carbon molding for cars) y guess any flexible and strong material could be used, like silicone, or even wheel tubes from trucks, i we have a problem with the material  we could use an inner material on the inside (like silicon bags, and a strong material on the outside. 

[articulo.mercadolibre.com.ar/MLA-834987029-bolsa-de-silicona-reutilizable-para-amasar-multifuncional-_JM?quantity=1#position=6&type=item&tracking_id=bfd6aca1-5a8f-4d6e-89b2-29789329285c](url)

what do you think of the mechanism?

**Comment by ovix-hub** [comment]
Me preocupa el control que podamos tener sobre el neoprene en relación al control preciso de volumen si el mismo se comporta de manera elástica.

**Comment by wahingt2n** [comment]
i think you have a valid point, i thought about the use ob pneumatic suspension bladders , but they are too hard to move, do you know the material of the ambu bottle?
and what do you think of the mechanical idea?
